// Generated by CoffeeScript 1.6.3
(function() {
  $("document").ready(function() {
    return $(".fonts").on('click', function() {
      $('.length1').attr('class', 'test length1');
      $('.length2').attr('class', 'test length2');
      $(".test").addClass($(this).attr("class").split(" ")[1]);
      return $('.width').text("" + ($('.length1').innerWidth()/20) + "em/" + ($('.length2').innerWidth()/20) + "em");
    });
  });

}).call(this);
